/*

CREATED: 1/10/2022

This dofile creates some descriptive statistics for the dataset and contains the main analysis for the project

Input:  master_data.dta
Output: coefficients of interest

*/

// Step 1: Identify candidates that are term limited and can't run and compare how often we see another candidate with the same last name relative to when a candidate voluntarily decides not to run

local merge               1
local preliminary         0
local election_unit       0
local names               0
local output              0
local test                0

clear all

if `merge'==1   {
clear all
use "${root}/term_limited_elections.dta", clear
// merge 1:1 caseid using  "${root}/lastname_data.dta", gen(mergem)
merge 1:1 caseid using  "${root}/lastname_data.dta", gen(mergem)
replace limited_seat=0 if limited_seat==.
bys election_id seat: egen limited_election=total(limited_seat) // gen election-level variable identifying if an election is a limited seat because the incumbent of that seat is term_limited and can't run
// replace limited_election=1 if limited_election!=0       // taking care of cases when limited_election==2 because of multimember districts - now taken care of by fact that limited_election got generated by seat

bys election_id: egen incumbents_running=total(incumbent)
gen open_contest=1 if incumbents_running==0
replace open_contest=0 if incumbents_running!=0

gen lastname_limited=same_lastname*limited_election
gen nepotism=1 if lastname_limited==1 & winner==1
replace nepotism=0 if nepotism==.
replace nepotism=0 if candidate_fullname=="ROCCA, TORY" & state==22 & year==2004 & legbranch==1
replace nepotism=1 if candidate_fullname=="CLARK, MARK" & state==3 & year==2000 & legbranch==1

// create a series of dummy variables
gen unopposed=1 if nr_cand==1
replace unopposed=0 if unopposed==.

gen one_opponent=1 if nr_cand==2
replace one_opponent=0 if one_opponent==.

gen two_opponents=1 if nr_cand==3
replace two_opponents=0 if two_opponents==.

gen multiple_opponents=1 if nr_cand>3
replace multiple_opponents=0 if multiple_opponents==.



cap save "${root}/analysis_dataset.dta", replace

/* SET UP AN OVERLEAF GITHUB LINK AND FIX PATHS ETC
esttab using "./graphs/guide80/regression1_1.tex", replace  ///
 b(3) se(3) nomtitle label star(* 0.10 ** 0.05 *** 0.01) ///
 booktabs alignment(D{.}{.}{-1}) ///
 title(My very first basic regression table \label{reg1})   ///
 addnotes("Dependent variable: Deaths (norm.). A lot of endogeneity in this specification." "Data source: Our World in Data COVID-19 database.")
*/
}


if `preliminary'==1 {   // ADD CODE TO EXPORT THIS TO LATEX TABLES

use "${root}/analysis_dataset.dta", clear

// DIFFERENT SPECIFICATIONS

reg winner same_lastname limited_election
reg winner same_lastname limited_election lastname_limited

reg winner same_lastname limited_election unopposed one_opponent two_opponents multiple_opponents
reg winner same_lastname limited_election lastname_limited unopposed one_opponent two_opponents multiple_opponents

cap preserve
drop if open_contest==0

reg winner same_lastname limited_election lastname_limited

reg winner same_lastname limited_election unopposed one_opponent two_opponents multiple_opponents

reg winner same_lastname limited_election lastname_limited unopposed one_opponent two_opponents multiple_opponents

restore



}

if `election_unit'==1 {

  use "${root}/analysis_dataset.dta", clear

  keep if winner==1

  gen single_cand_election=1 if nr_cand==1
  replace single_cand_election=0 if single_cand_election==.

preserve
drop if open_contest==0
reg same_lastname limited_election // this is the specification where LHS=1 if winner of that election has the same last name as previous incumbent and RHS is whether this is a term limited election
reg single_cand_election limited_election same_lastname lastname_limited
restore

save "${root}/election_level_data.dta", replace

}


if `test'==1 {
import excel "C:\Users\ei87\Dropbox (YLS)\Term Limits\Dataset\temp.xlsx", firstrow clear
rename *, lower
drop nr
rename (fm g) (inc_g suc_g)
count if inc_g=="M" & suc_g=="M"
count if inc_g=="M" & suc_g=="F"
count if inc_g=="F" & suc_g=="M"
count if inc_g=="F" & suc_g=="F"

}


if `output'==1 {

 use "${root}/analysis_dataset.dta", clear

eststo: reg winner same_lastname limited_election
esttab using example.tex, label

}
